# Generated by Django 5.0.3 on 2024-04-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuario_perfil_alter_usuario_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='run',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='apellidos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='nombres'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.IntegerField(blank=True, null=True, primary_key=True, serialize=False, verbose_name='rut'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='password'),
        ),
    ]
