# Generated by Django 5.0.3 on 2024-04-26 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id modelo')),
                ('nombre_categoria', models.CharField(max_length=60, verbose_name='categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.IntegerField(primary_key=True, serialize=False, verbose_name='id inventario')),
                ('modelo', models.CharField(max_length=30, verbose_name='modelo')),
                ('talla', models.IntegerField(verbose_name='talla')),
                ('valor', models.IntegerField(verbose_name='valor')),
                ('imagen', models.ImageField(null=True, upload_to='inventario/', verbose_name='imagen del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
