# Generated by Django 5.0.3 on 2024-04-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
